name: Flutter Package Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      # Uncomment if you have tests
      # - name: Run tests
      #   run: flutter test

      - name: Extract version
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d '+' -f1)

          if [ -z "$VERSION" ]; then
            echo "Failed to extract version from pubspec.yaml"
            exit 1
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if version already released
        id: tag_check
        run: |
          git fetch --tags

          if git tag -l "v${VERSION}" | grep -q .; then
            echo "Version v${VERSION} already released."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Version v${VERSION} not released yet."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          VERSION: ${{ env.VERSION }}

      - name: Skip existing release
        if: steps.tag_check.outputs.exists == 'true'
        run: |
          echo "Tag v${VERSION} already exists. Nothing to do."
          exit 0
        env:
          VERSION: ${{ env.VERSION }}

      - name: Configure pub.dev credentials
        run: |
          mkdir -p ~/.pub-cache
          echo '${{ secrets.PUB_CREDENTIALS }}' > ~/.pub-cache/credentials.json

      - name: Verify pub credentials
        run: |
          ls -la ~/.pub-cache
          cat ~/.pub-cache/credentials.json | head
          echo "Secret..."
          echo '${{ secrets.PUB_CREDENTIALS }}'
          echo "Credentials..."
          cat ~/.pub-cache/credentials.json

      - name: Debug Dart
        run: |
          dart --version
          flutter --version

      - name: Verify authentication
        run: dart pub token list

      - name: Validate package
        run: flutter pub publish --dry-run

      - name: Publish package
        run: flutter pub publish --force

      - name: Create and push tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag "v${VERSION}"
          git push origin "v${VERSION}"
        env:
          VERSION: ${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          generate_release_notes: true